### ISSUE TITLE
Authentication to mailbox server failed: Can't login to this server

### ISSUE THREAD

**Issue by aklik** [kevinoid/auth-mailbox-joomla#8]
Hi, I was trying to make it work on my server. From whatever reason I receive the following error: "Authentication to mailbox server failed: Can't login to this server" Any idea what can it be? I ran a telnet test connection on the host against the mailbox server's ports.. everything is ok, but in joomla (using Joomla 3.2.3 version).. nothing..none of the options are working, secured or not secured..  Any hint would be welcomed. Thanks!

**Comment by kevinoid** [comment]
I ran into the `Warning: You cannot access the private section of this site.` message and tracked it down to an autoregistration failure.  In my case autoregistration was failing because the username with the configured domain appended did not pass Joomla's internal email address validation, causing the user creation to fail.

If you (or anyone else) runs into a similar error message and the user does not appear in User Management, you can check if this is the cause by changing the log statement at [plugins/user/joomla/joomla.php:364](https://github.com/joomla/joomla-cms/blob/3.6.3/plugins/user/joomla/joomla.php#L364) to read:

    JLog::add('Error in autoregistration for user ' . $user['username'] . ': ' . $instance->getError() . '.', JLog::WARNING, 'jerror');

Changing `'error'` to `'jerror'` will cause the error to be displayed to the user and adding `$instance->getError()` will get the error which occurred during the user save attempt.  Feel free to reopen this issue or create another one with the additional warning information.
