### ISSUE TITLE
User is not being created

### ISSUE THREAD

**Issue by jimorillo** [kevinoid/auth-mailbox-joomla#9]
Hi, I am trying to login using this plugin but thought it authenticates with the mailbox server, the user is not being created and I get this error. 

Warning
You cannot access the private section of this site.

I think it is because the user is not being registered at all. I have tried using the plugin with "Allow User Registration" On and Off with no results.

Thanks for any help you could bring.

**Comment by kevinoid** [comment]
Thanks for taking the time to write out the necessary code for a workaround @jimorillo.  I'm sorry it has taken me so long to respond and to move on the issue.

I was able to reproduce the `Warning: You cannot access the private section of this site.` message and tracked it down to an autoregistration failure.  In my case autoregistration was failing because the username with the configured domain appended did not pass Joomla's internal email address validation, causing the user creation to fail.

Looking back through this issue, I suspect autoregistration may have been the underlying cause of your issue as well.  I know old versions of Joomla rejected hyphens in usernames, which could have caused the name `user-email` to fail during autoregistration.  Luckily that shouldn't be an issue anymore.

Do you know if your additional code for user creation is required for current versions of Joomla?  If it is, or if you (or anyone else) runs into a similar error message and the user does not appear in User Management after successful login, you can check if this is the cause by changing the log statement at [plugins/user/joomla/joomla.php:364](https://github.com/joomla/joomla-cms/blob/3.6.3/plugins/user/joomla/joomla.php#L364) to read:

    JLog::add('Error in autoregistration for user ' . $user['username'] . ': ' . $instance->getError() . '.', JLog::WARNING, 'jerror');

Changing `'error'` to `'jerror'` will cause the error to be displayed to the user and adding `$instance->getError()` will get the error which occurred during the user save attempt.  Feel free to reopen this issue or create another one with the additional warning information.

I think the issue is solved for current versions of Joomla and the auth-mailbox plugin, but if not please feel free to reopen the issue.
